export const projectConstant = {
  ADD_PROJECT: "ADD_PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT",
  UPDATE_PROJECT: "UPDATE_PROJECT",
  GET_PROJECTS: "GET_PROJECTS",
  GET_PROJECT: "GET_PROJECT",
  PROJECT_ERROR: "PROJECT_ERROR",
  SET_LOADING: "SET_LOADING",
  CLEAR_LOADING: "CLEAR_LOADING",
  CLEAR_ERROR: "CLEAR_ERROR",
  CLEAR_PROJECT: "CLEAR_PROJECT",
  CLEAR_PROJECTS: "CLEAR_PROJECTS",
  SET_PROJECT: "SET_PROJECT",
  SET_PROJECTS: "SET_PROJECTS"
};
